spring.application.name=PortfolioManagmentApplication
spring.profiles.default=local
spring.web.resources.static-locations=classpath:/static/,file:./frontend/
yahoo.api.connect-timeout-ms=2500
yahoo.api.read-timeout-ms=5000
